Enemy
PMM-Dev/moonshot pull request #1
Opened 2020-11-12 12:39 UTC by Leejeongseok0407

make a EnemyMove.cs, Rabbit.prefab

apply Move.cs and I made sure it works

Move by referring to "wayPoint".
It moves through the current index, and if the current index is 0 or equals the length of the array, it moves by referencing in reverse order of progression.

적움직임 스크립트, 토끼 프리팹을 만들었음

적움직입 스크립트가 잘 작동하는것을 확인하였고

"wayPoint"를 참조하여 이동합니다.
현재 인덱스를 통해 이동하며 현재 인덱스가 0이거나 배열 길이와 같으면 진행의 역순으로 참조하여 이동합니다.

2020-11-12 12:56 UTC, ManaBingsu requested changes
Naming convention이 지켜지지 않았습니다.

2020-11-12 12:56 UTC, ManaBingsu commented on Assets/2.Scripts/Enemy/EnemyMove.cs
> +        int indexAdd = 1;
Name Convention 0. 기본적으로 모든 필드는 private로 선언하며 밑줄을 붙여준다.
ex ) GameObject[] wayPoints;-> private GameObject[] _wayPoints;

2020-11-13 05:11 UTC, ManaBingsu approved these changes, later dismissed

2020-11-13 06:09 UTC, Leejeongseok0407 commented on Assets/2.Scripts/Enemy/EnemyMove.cs
> +        int indexAdd = 1;
수정했습니다.

2020-11-13 08:00 UTC, ManaBingsu approved these changes

2020-11-13 11:39 UTC, merged