feat : BossPattern
PMM-Dev/moonshot pull request #41
Opened 2020-11-23 18:28 UTC by Leejeongseok0407

보스 패턴 만들었습니다.

총 네가지 패턴으로
1. 노래하기(소환)
2. 화내기(운석소환)
3. 모자 부메랑
4. 레이저로 긁기
가 있으며

노래하기의 _maxSpownCount는 적은 값으로 해야 무한 루프에 안빠집니다.
상속할떄 필요없는 프로퍼티를 제거해야 하는데 차후에 진행하겠습니다.

2020-11-23 18:30 UTC, Leejeongseok0407 commented
변수 제거 계획

패턴중에 오브젝트의 속도가 필요없는것과 필요한것으로 한번 더 나눌 예정
필요한것 : 모자 부메랑, 화냄 패턴
필요 없는것 : 소환, 레이저

2020-11-23 23:39 UTC, sjmjys954646 submitted a review, later dismissed

2020-11-24 01:10 UTC, ManaBingsu approved these changes, later dismissed

2020-11-24 01:10 UTC, ManaBingsu commented on Assets/2.Scripts/Enemy/Boss/MadPattern.cs
> +        private float _spwonInterval = 0.5f;
제가 생각하는 몬스터 소환의 뜻이라면 _spawnInterval 입니다.

2020-11-24 01:10 UTC, ManaBingsu commented on Assets/2.Scripts/Enemy/Boss/Projectile/Brass.cs
> +    public class Brass : Projectile
Brass -> Breath

2020-11-24 02:57 UTC, Kwon770 requested changes
NullReferenceException 뜨는데 확인해주세요

2020-11-24 02:57 UTC, Kwon770 commented on Assets/2.Scripts/Enemy/Boss/HatPattern.cs
> +            _hat.TargetPlayerPosition();
NullReferenceException: Object reference not set to an instance of an object
Enemy.HatPattern+<Run>d_2.MoveNext () (at Assets/2.Scripts/Enemy/HatPattern.cs:24)

2020-11-24 02:59 UTC, Kwon770 commented
그리고 Moon이 사용하는 여러 스크립트 (Projectile.cs 같은)에서 Player를 사용하던데, 현재 어떤식으로 Player 얻나요? FindObjectType 안보인는 같던데

2020-11-24 05:33 UTC, Leejeongseok0407 commented
@Kwon770 모든 패턴 스크립트를 관리하는 PatternController에서 배분 해줍니다.

2020-11-24 05:35 UTC, Leejeongseok0407 commented on Assets/2.Scripts/Enemy/Boss/HatPattern.cs
> +            _hat.TargetPlayerPosition();
플레이어가 존재하지 않아서 그런것 같습니다.
PatternController에 플레이어가 들어 있나요..?
제가 미리 언급해줘야 했는데 까먹은것 같네요

2020-11-24 08:49 UTC, Kwon770 approved these changes

2020-11-24 08:50 UTC, merged